import './globals.css'
import { Inter } from 'next/font/google'
import Script from 'next/script';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'TOP-Project',
  description: 'Generated by Team 4',
}


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
      {/* <Script src="https://cdn.anychart.com/releases/8.11.1/geodata/countries/united_states_of_america/united_states_of_america.js"></Script> */}
    </html>
  )
}
